### ISSUE TITLE
Slack Notifications

### ISSUE THREAD

**Issue by djurovicigoor** [YorCreative/Laravel-Query-Watcher#9]
Hello,

Do you plan to add support for Slack notifications?

**Comment by yordadev** [comment]
Hi @djurovicigoor 

Thank you for this issue! I do plan to add that, and much more. 
Time has been tight lately though. I will leave this issue open.

If you or anyone else reading this wanting slack notifications before I get a chance to do it and test it.

Here is how:

The major lift is already done with the [NotificationStrategy](https://github.com/YorCreative/Laravel-Query-Watcher/blob/main/src/Strategies/NotificationStrategy/NotificationStrategy.php) class.

All that is needed is to add the `slack` channel configuration in the [config](https://github.com/YorCreative/Laravel-Query-Watcher/blob/main/config/querywatcher.php).  

Take a gander at the [Discord Channel Notification](https://github.com/YorCreative/Laravel-Query-Watcher/blob/main/src/Strategies/NotificationStrategy/Channels/Discord.php)

In the same namespace, create a class that implements the [NotificationChannelInterface](https://github.com/YorCreative/Laravel-Query-Watcher/blob/main/src/Strategies/NotificationStrategy/NotificationChannelInterface.php) called `Slack`.

The only thing to do is to put the Http::post() call over to slack in the `Notify(...)` method.

The NotificationStrategy will handle the rest.
-----

I need to add the above to the readme. 💡 
If you want to attempt to do it and get stuck, post back here and I'll answer any questions!

**Comment by yordadev** [comment]
@djurovicigoor  Enjoy 🥂
